### PR TITLE
Prevent user select on selected table row

### PR DESCRIPTION
**Pull request by JPLachance**
I added "user-select: none " on selected table row. It prevent weird selections on double click. What do you think?

### CODE REVIEW

**Comment by wfortin** [comment]
This is kinda sad, because sometimes you want to actually select text...

**Comment by JPLachance** [comment]
Right, but you can select the text if the row is not the selected one. I checked in GG Drive and you simply cannot select the text of any row. It's not that bad in our app if the user can simply unselect the row to select the text (except the case when he got only one row).

**Comment by wfortin** [comment]
Ah, i did't figure that it was only the selected row, but @GermainBergeron 's solution looks great.

**Comment by JPLachance** [comment]
Drop! We will remove user selection using JavaScript on double click instead.

**Pull request closed without merging**
